### ISSUE TITLE
Add IPv6 support

### ISSUE THREAD

**Issue by lapo-luchini** [tykling/gstat_exporter#3]
I managed to do using this:

```patch
-start_http_server(9248)
+start_http_server(9248, '::')
```

But it is probably the default behavior if dependency is updated, as prometheus/client_python#657 has landed.

Edit: not really, that patch allows using IPv6 addresses, but still has `0.0.0.0` as default listen address.

**Comment by tykling** [comment]
support for listening on ipv6 addresses was added in 5e9b5699a39cf44bd5dd7d8f7d07a9942cf668cf

**Comment by tykling** [comment]
this is available in the v0.2.0 release tagged today https://github.com/tykling/gstat_exporter/releases/tag/v0.2.0
