### ISSUE TITLE
Continues to export removed disks

### ISSUE THREAD

**Issue by asomers** [tykling/gstat_exporter#5]
If you start the gstat_exporter and then remove a disk, the exporter will continue to publish that disk's last snapshot forever.  Instead, it should remove that disk's metrics.

**Comment by tykling** [comment]
Thank you for the report! This feature has been added somewhere after 0.1 starting with this commit 6c53cd68b5e54be2545b38913d00b68c189f100a and will be in the next release :) :+1:

**Comment by tykling** [comment]
this is available in the v0.2.0 release tagged today https://github.com/tykling/gstat_exporter/releases/tag/v0.2.0

**Comment by asomers** [comment]
Thank you!
